
Vagrant.configure("2") do |config|

  config.vm.box = "ol7-latest"
  config.vm.box_url = "https://yum.oracle.com/boxes/oraclelinux/latest/ol7-latest.box"
  config.vm.box_check_update = false
  config.vm.synced_folder "shared/", "/shared", create: true
  config.vm.network "forwarded_port", guest: 5432, host: 5432

  config.vm.define "PG11" do |pg|

    pg.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--audio", "none"]
      vb.name = "PostgreSQL"
      vb.cpus = 2
      vb.memory = 4096
    end

    pg.vm.hostname = "pg11.btg.com"
    pg.vm.network :private_network, ip: "192.168.14.102"
    pg.vm.provision "shell", path: "scripts/install.sh"
   
  end
  
end
