
Vagrant.configure("2") do |config|

  config.vm.box = "ol7-latest"
  config.vm.box_url = "https://yum.oracle.com/boxes/oraclelinux/latest/ol7-latest.box"
  config.vm.box_check_update = false
  config.vm.synced_folder "shared/", "/shared", create: true
  config.vm.network "forwarded_port", guest: 27017, host: 27017

  config.vm.define "mongoDB" do |mongo|
    
    mongo.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--audio", "none"]
      vb.name = "mongoDB"
      vb.cpus = 2
      vb.memory = 4096
    end

    mongo.vm.hostname = "mongodb.btg.com"
    mongo.vm.network :private_network, ip: "192.168.14.100"
    mongo.vm.provision "file", source: "files/mongodb-org-4.0.repo", destination: "/tmp/mongodb-org-4.0.repo"
    mongo.vm.provision "file", source: "files/influxdb.repo", destination: "/tmp/influxdb.repo"
    mongo.vm.provision "file", source: "files/mongod.conf", destination: "/tmp/mongod.conf"
    mongo.vm.provision "file", source: "files/telegraf.conf", destination: "/tmp/telegraf.conf"
    mongo.vm.provision :shell, path: "files/provision.sh"
  end
  
end
